version: "3.4"
services:
  assets:
    build:
      context: ./assets
      target: dev-server
    volumes:
      - ./dist:/assets/dist:rw
      - ./assets/src:/assets/src:rw
    ports:
      - "8080:8080"
      - "8081:8081"
