version: "3"
volumes:
  dist:
services:
  client:
    build:
      context: ./client
    command: "yarn start"
    ports:
      - "8080:8080"
      - "8081:8081"
  server:
    build:
      context: ./server
    ports:
      - "9000:9000"
    volumes:
      - dist:/service/dist:ro
