FROM node:8.11.1 as builder

WORKDIR /assets

# install
COPY ./webpack.config.js /assets/webpack.config.js
COPY ./serve.config.js /assets/serve.config.js
COPY ./package.json /assets/package.json
COPY ./yarn.lock /assets/yarn.lock

RUN yarn install

COPY ./src /assets/src
RUN yarn build:prod

# --- production ---
FROM nginx:1.14-alpine
COPY --from=builder /assets/dist /usr/share/nginx/html
EXPOSE 80
